name: 'Hasura Cloud Preview App'
description: 'Hasura Cloud preview app with metadata migrations from your GitHub branch'
inputs:
  name:
    description: 'Name of the preview app'
    required: true
    default: 'cloud_free'
  region:
    description: 'Region to deploy preview app in'
    required: false
    default: 'us-east-2'
  plan:
    description: 'Plan of the preview app'
    required: false
    default: 'cloud_free'
  hasuraCloudGraphQLEndpoint:
    description: 'GraphQL endpoint of Hasura Cloud data service'
    required: false
    default: 'https://data.pro.hasura.io/v1/graphql'
  hasuraCloudAccessToken:
    description: 'Hasura Cloud personal access token for contacting the Hasura Cloud APIs'
    required: true
outputs:
  graphQLEndpoint:
    description: 'GraphQL endpoint of the created preview app'
  consoleURL:
    description: 'Console URL of the created preview app'
runs:
  using: 'node12'
  main: 'dist/index.js'
