name: 'Hasura Cloud Preview App'
description: 'Hasura Cloud preview app with metadata migrations from your GitHub branch'
inputs:
  name:
    description: 'Name of the preview app'
    required: true
    default: 'cloud_free'
  hasuraCloudAccessToken:
    description: 'Hasura Cloud personal access token for contacting the Hasura Cloud APIs'
    required: true
  region:
    description: 'Region to deploy preview app in'
    required: false
    default: 'us-east-2'
  plan:
    description: 'Plan of the preview app'
    required: false
    default: 'cloud_free'
  hasuraCloudGraphQLEndpoint:
    description: 'GraphQL endpoint of Hasura Cloud data service'
    required: false
    default: 'https://data.pro.hasura.io/v1/graphql'
  hasuraProjectDirectoryPath:
    description: 'Path to the directory of the Hasura project in the repo. If empty, root is considered to be a Hasura project.'
    required: false
    default: ''
  hasuraEnv:
    description: 'Set of environment variables that you wish to provide to the created preview app. Example: HASURA_GRAPHQL_JWT_SECRET, PG_DATABASE_URL etc'
    required: false
    default: ''
outputs:
  graphQLEndpoint:
    description: 'GraphQL endpoint of the created preview app'
  consoleURL:
    description: 'Console URL of the created preview app'
runs:
  using: 'node12'
  main: 'dist/index.js'
